import 'package:flutter/material.dart';
import 'package:aroosi_flutter/core/responsive.dart';
import 'package:aroosi_flutter/theme/theme_helpers.dart';
import 'package:aroosi_flutter/widgets/app_scaffold.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Privacy Policy',
      usePadding: false,
      child: ResponsiveBuilder(
        builder: (context, screenType) {
          return CustomScrollView(
            slivers: [
              SliverPadding(
                padding: Responsive.screenPadding(
                  context,
                ).copyWith(top: 24, bottom: 32),
                sliver: SliverList(
                  delegate: SliverChildListDelegate([
                    _buildPrivacyContent(context),
                  ]),
                ),
              ),
            ],
          );
        },
      ),
    );
  }

  Widget _buildPrivacyContent(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildSection(
          context: context,
          title: 'Overview',
          content: '''
      Aroosi uses Firebase services to power authentication, messaging, analytics, performance monitoring, and secure storage. This policy explains what data each SDK collects, how it is collected, how we use it, and how you can manage or delete your information.

      We do not sell personal data. We share necessary information with Google LLC (Firebase) solely to deliver app functionality, improve stability, and send opted-in notifications.''',
        ),
        _buildSection(
          context: context,
          title: 'Firebase SDK Data Collection',
          content: '''
      **Firebase Authentication**
      • Data collected: email address, optional phone number, hashed password, Firebase UID, authentication tokens
      • Collection method: provided directly by you during sign up, login, or account recovery
      • Purpose: create and secure accounts, prevent fraud, support sign-in on multiple devices

      **Cloud Firestore**
      • Data collected: profile details (display name, age range, city or region supplied by you), match preferences, chat metadata, consent choices, moderation flags
      • Collection method: information you enter in the app or that results from your interactions (e.g., messaging, matches)
      • Purpose: power matching, conversations, cultural compatibility, and safety workflows

      **Firebase Storage**
      • Data collected: profile photos and voice notes you upload
      • Collection method: files you choose to share through the media picker
      • Purpose: safely store and deliver the content you upload to other users

      **Firebase Cloud Messaging & APNs**
      • Data collected: Firebase Installation ID, APNs device token, notification interaction data (opens, dismissals)
      • Collection method: automatically generated by the SDK when you grant notification permission
      • Purpose: deliver match, message, and security notifications you opt in to receive

      **Firebase Analytics / Google Analytics for Firebase**
      • Data collected: app instance ID, session timestamps, screen views, feature usage events, coarse device information (model, OS version, carrier, IP truncated by Google)
      • Collection method: automatically after you grant analytics consent in the privacy settings; you can toggle this off at any time
      • Purpose: understand which features are used, improve onboarding, monitor funnel drop-off, and plan roadmap changes

      **Firebase Performance Monitoring**
      • Data collected: anonymized network request metadata (domain, latency, success/failure), app start and screen render timings, device performance metrics (CPU, memory)
      • Collection method: automatic once you opt in to diagnostics in privacy settings
      • Purpose: detect outages, reduce load times, and optimize network efficiency

      **Firebase Crashlytics & Firebase Sessions**
      • Data collected: crash stack traces, device state at crash time (model, OS version, free RAM and storage), anonymized session IDs
      • Collection method: automatic when a crash or fatal error occurs; respects your diagnostics opt-in
      • Purpose: investigate stability issues, reproduce bugs, and maintain app reliability

      **Firebase Installations**
      • Data collected: unique Firebase Installation ID linked to your device
      • Collection method: automatic on first app launch
      • Purpose: support token management, analytics deduplication, and targeted notifications

      We do not collect precise GPS location, Bluetooth, contacts, or health data. Any location fields shown in your profile are supplied manually by you.''',
        ),
        _buildSection(
          context: context,
          title: 'How Data Is Collected',
          content: '''
      • Direct input: information you enter in forms, profile fields, and messages
      • Media selection: photos and audio you explicitly upload via the picker
      • Automatic collection (with consent): diagnostic and analytics data captured by Firebase SDKs after you opt in through the privacy dialog or settings screen
      • Required operational data: authentication tokens and installation IDs needed to keep your session secure and to send notifications you request

      We provide consent prompts before enabling analytics, performance, or notification tracking. You can revisit Settings → Privacy at any time to withdraw consent.''',
        ),
        _buildSection(
          context: context,
          title: 'How We Use Your Data',
          content: '''
      • Account security: authenticate logins, protect against unauthorized access, and provide password recovery
      • Core functionality: deliver matching, messaging, cultural compatibility, and moderation features
      • Communications: send opted-in notifications about matches, messages, and important account updates
      • Analytics and product decisions: understand aggregated feature usage to improve onboarding and prioritize roadmap work (only when consented)
      • Diagnostics: monitor crashes, performance regressions, and network outages so we can keep the app reliable

      We never use Firebase data for advertising or profiling outside of Aroosi.''',
        ),
        _buildSection(
          context: context,
          title: 'Data Sharing & Third Parties',
          content: '''
      We partner with Google LLC (Firebase) to process the data listed above. Google acts as our data processor and stores information in Google Cloud data centers that comply with ISO 27001, SOC 2 Type II, GDPR, and CCPA requirements.

      Additional third parties:
      • Apple Push Notification service (APNs) – delivers iOS notifications using your APNs token
      • Google Cloud (as part of Firebase) – hosts databases, storage, analytics, and diagnostics

      We do not allow third parties to use your data for their own advertising. Any subcontractors engaged by Firebase must offer equal or stronger data protections under their Data Processing Terms.

      If we integrate additional vetted providers, we will update this policy and notify you in-app.''',
        ),
        _buildSection(
          context: context,
          title: 'Retention & Deletion',
          content: '''
      • Account data (email, profile, settings): kept while your account is active; removed within 30 days after confirmed deletion request
      • Messages and safety logs: retained for up to 6 months after deletion to investigate abuse reports, then purged
      • Uploaded media: deleted from Firebase Storage during account deletion or when you remove the asset
      • Analytics and diagnostics: stored by Google for up to 13 months, then aggregated or deleted per Firebase retention defaults

      You can request deletion or a copy of your data at any time via Settings → Privacy. We respond within 30 days and delete backups within a reasonable operational window unless law or safety obligations require longer retention.''',
        ),
        _buildSection(
          context: context,
          title: 'Your Rights & Contact',
          content: '''
      • Access, correct, or delete your personal information
      • Withdraw consent for analytics, performance, or notifications without affecting core account access
      • Lodge a complaint with your local data protection authority if you believe your rights are infringed

      Contact us at privacy@aroosi.af or by mail at: Privacy Officer, Aroosi, Kabul, Afghanistan.

      Last updated: 10 November 2025''',
        ),
        const SizedBox(height: 32),
        _buildActionButtons(context),
        const SizedBox(height: 32),
      ],
    );
  }

  Widget _buildSection({
    required BuildContext context,
    required String title,
    required String content,
  }) {
    final theme = ThemeHelpers.getMaterialTheme(context);
    final colorScheme = theme.colorScheme;
    final textTheme = theme.textTheme;

    return Container(
      margin: const EdgeInsets.only(bottom: 24),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: colorScheme.surface,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: colorScheme.shadow.withValues(alpha: 0.08),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
              color: colorScheme.primary,
            ),
          ),
          const SizedBox(height: 12),
          Text(
            content,
            style: textTheme.bodyMedium?.copyWith(
              height: 1.5,
              color: colorScheme.onSurfaceVariant,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildActionButtons(BuildContext context) {
    final colorScheme = ThemeHelpers.getMaterialTheme(context).colorScheme;
    return Column(
      children: [
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            onPressed: () {
              // Navigate to data download page or contact support
            },
            icon: const Icon(Icons.download),
            label: const Text('Request My Data'),
            style: ElevatedButton.styleFrom(
              backgroundColor: colorScheme.primary,
              foregroundColor: colorScheme.onPrimary,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ),
        const SizedBox(height: 16),
        SizedBox(
          width: double.infinity,
          child: OutlinedButton.icon(
            onPressed: () {
              // Navigate to delete account page or contact support
            },
            icon: const Icon(Icons.delete_outline),
            label: const Text('Delete My Account'),
            style: OutlinedButton.styleFrom(
              foregroundColor: colorScheme.error,
              side: BorderSide(color: colorScheme.error),
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ),
      ],
    );
  }
}
